language: node_js

node_js:
  - "stable"

# before_install:
# install:
# before_script:

  script:
  - npm run lint
  # - npm run test
  # - npm run test:coveralls

# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy:

notifications:
  email: false

